networks:
  rossel-kafka.network:
    driver: bridge

services:
  php:
    build:
      context: ./
      dockerfile: docker/php/Dockerfile
    restart: always
    volumes:
      - .:/var/www/app.dev
    networks:
      - rossel-kafka.network
    tty: true
    ports:
      - "9096:9000"
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      - PHP_IDE_CONFIG=serverName=php.rossel-kafka-php-kit
      - XDEBUG_MODE=${XDEBUG_MODE}
