services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Rossel\RosselKafka\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Model/'
      - '../src/Enum/'
      - '../src/Exception/'
      - '../src/RosselKafkaPhpKitBundle.php'

  _instanceof:
    Rossel\RosselKafka\Consumption\Consumer\ConsumerInterface:
      tags: ['rossel_kafka.consumer']

  Rossel\RosselKafka\Consumption\Manager\ConsumptionManager:
    $consumers: !tagged_iterator 'rossel_kafka.consumer'
