<?php

declare(strict_types=1);

namespace Rossel\RosselKafka\Tests\Model;

use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\Attributes\Test;
use PHPUnit\Framework\TestCase;
use Rossel\RosselKafka\Enum\MessageHeaders\Area;
use Rossel\RosselKafka\Enum\MessageHeaders\MessageType;
use Rossel\RosselKafka\Model\MessageHeaders;

final class MessageHeadersTest extends TestCase
{
    // -------------------------------------------------------------------------
    // Track ID
    // -------------------------------------------------------------------------

    #[Test]
    public function trackIdAutoGeneratedWhenNull(): void
    {
        $headers = $this->buildHeaders(trackId: null);

        self::assertMatchesRegularExpression(
            '/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i',
            $headers->getTrackId(),
            'Track ID should be a valid UUID4.',
        );
    }

    #[Test]
    public function trackIdKeptWhenProvided(): void
    {
        $headers = $this->buildHeaders(trackId: 'my-custom-track-id');

        self::assertSame('my-custom-track-id', $headers->getTrackId());
    }

    #[Test]
    public function twoInstancesWithNullTrackIdGetDifferentUuids(): void
    {
        $a = $this->buildHeaders(trackId: null);
        $b = $this->buildHeaders(trackId: null);

        self::assertNotSame($a->getTrackId(), $b->getTrackId());
    }

    // -------------------------------------------------------------------------
    // Date / time
    // -------------------------------------------------------------------------

    #[Test]
    public function dateTimeAutoSetWhenNull(): void
    {
        $before = new \DateTimeImmutable();
        $headers = $this->buildHeaders(dateTime: null);
        $after = new \DateTimeImmutable();

        self::assertGreaterThanOrEqual($before, $headers->getDateTime());
        self::assertLessThanOrEqual($after, $headers->getDateTime());
    }

    #[Test]
    public function dateTimeKeptWhenProvided(): void
    {
        $dt = new \DateTimeImmutable('2024-06-15T12:00:00+00:00');
        $headers = $this->buildHeaders(dateTime: $dt);

        self::assertSame($dt, $headers->getDateTime());
    }

    // -------------------------------------------------------------------------
    // Fallbacks
    // -------------------------------------------------------------------------

    #[Test]
    public function dateTimeOriginalFallsBackToDateTimeWhenNull(): void
    {
        $dt = new \DateTimeImmutable('2024-06-15T12:00:00+00:00');
        $headers = $this->buildHeaders(dateTime: $dt, dateTimeOriginal: null);

        self::assertSame($dt, $headers->getDateTimeOriginal());
    }

    #[Test]
    public function dateTimeOriginalKeptWhenProvided(): void
    {
        $dt = new \DateTimeImmutable('2024-06-15T12:00:00+00:00');
        $original = new \DateTimeImmutable('2024-01-01T00:00:00+00:00');
        $headers = $this->buildHeaders(dateTime: $dt, dateTimeOriginal: $original);

        self::assertSame($original, $headers->getDateTimeOriginal());
    }

    #[Test]
    public function fromOriginalFallsBackToFromWhenNull(): void
    {
        $headers = $this->buildHeaders(from: 'app-a', fromOriginal: null);

        self::assertSame('app-a', $headers->getFromOriginal());
    }

    #[Test]
    public function fromOriginalKeptWhenProvided(): void
    {
        $headers = $this->buildHeaders(from: 'app-a', fromOriginal: 'app-original');

        self::assertSame('app-original', $headers->getFromOriginal());
    }

    #[Test]
    public function trackIdOriginalFallsBackToTrackIdWhenNull(): void
    {
        $headers = $this->buildHeaders(trackId: 'tid-123', trackIdOriginal: null);

        self::assertSame('tid-123', $headers->getTrackIdOriginal());
    }

    #[Test]
    public function trackIdOriginalKeptWhenProvided(): void
    {
        $headers = $this->buildHeaders(trackId: 'tid-123', trackIdOriginal: 'tid-original');

        self::assertSame('tid-original', $headers->getTrackIdOriginal());
    }

    // -------------------------------------------------------------------------
    // Version
    // -------------------------------------------------------------------------

    #[Test]
    public function versionDefaultsToOne(): void
    {
        $headers = $this->buildHeaders();

        self::assertSame(MessageHeaders::DEFAULT_VERSION, $headers->getVersion());
    }

    #[Test]
    public function versionCanBeOverridden(): void
    {
        $headers = $this->buildHeaders(version: '2');

        self::assertSame('2', $headers->getVersion());
    }

    // -------------------------------------------------------------------------
    // toArray
    // -------------------------------------------------------------------------

    #[Test]
    public function toArrayContainsAllFixedKeys(): void
    {
        $dt = new \DateTimeImmutable('2024-06-15T12:00:00+00:00');
        $headers = $this->buildHeaders(
            area: Area::FRANCE,
            from: 'my-app',
            messageType: MessageType::LOG,
            trackId: 'track-1',
            dateTime: $dt,
            dateTimeOriginal: $dt,
            fromOriginal: 'original-app',
            trackIdOriginal: 'track-original',
            version: '1',
        );

        $array = $headers->toArray();

        self::assertSame('FR', $array[MessageHeaders::KEY_AREA]);
        self::assertSame($dt->format(\DateTimeInterface::ATOM), $array[MessageHeaders::KEY_DATE_TIME]);
        self::assertSame($dt->format(\DateTimeInterface::ATOM), $array[MessageHeaders::KEY_DATE_TIME_ORIGINAL]);
        self::assertSame('my-app', $array[MessageHeaders::KEY_FROM]);
        self::assertSame('original-app', $array[MessageHeaders::KEY_FROM_ORIGINAL]);
        self::assertSame('LOG', $array[MessageHeaders::KEY_MESSAGE_TYPE]);
        self::assertSame('track-1', $array[MessageHeaders::KEY_TRACK_ID]);
        self::assertSame('track-original', $array[MessageHeaders::KEY_TRACK_ID_ORIGINAL]);
        self::assertSame('1', $array[MessageHeaders::KEY_VERSION]);
    }

    #[Test]
    public function toArrayIncludesAdditionalHeaders(): void
    {
        $headers = new MessageHeaders(
            area: Area::FRANCE,
            from: 'app',
            messageType: MessageType::LOG,
            additionalHeaders: ['custom-key' => 'custom-value', 'x-correlation-id' => 'corr-123'],
        );

        $array = $headers->toArray();

        self::assertSame('custom-value', $array['custom-key']);
        self::assertSame('corr-123', $array['x-correlation-id']);
    }

    #[Test]
    public function toArrayFixedHeadersHavePriorityOverAdditional(): void
    {
        // 'area' is a fixed key — the additional header must not override it
        $headers = new MessageHeaders(
            area: Area::FRANCE,
            from: 'app',
            messageType: MessageType::LOG,
            additionalHeaders: [MessageHeaders::KEY_AREA => 'BE'],
        );

        self::assertSame('FR', $headers->toArray()[MessageHeaders::KEY_AREA]);
    }

    #[Test]
    public function additionalHeadersGetterReturnsProvidedHeaders(): void
    {
        $additional = ['foo' => 'bar'];
        $headers = new MessageHeaders(
            area: Area::FRANCE,
            from: 'app',
            messageType: MessageType::LOG,
            additionalHeaders: $additional,
        );

        self::assertSame($additional, $headers->getAdditionalHeaders());
    }

    // -------------------------------------------------------------------------
    // Getters
    // -------------------------------------------------------------------------

    #[Test]
    public function gettersReturnCorrectValues(): void
    {
        $headers = new MessageHeaders(
            area: Area::BELGIUM,
            from: 'service-x',
            messageType: MessageType::EXEC_ERROR,
        );

        self::assertSame(Area::BELGIUM, $headers->getArea());
        self::assertSame('service-x', $headers->getFrom());
        self::assertSame(MessageType::EXEC_ERROR, $headers->getMessageType());
    }

    // -------------------------------------------------------------------------
    // Dataset providers
    // -------------------------------------------------------------------------

    /**
     * @return iterable<string, array{Area}>
     */
    public static function areaProvider(): iterable
    {
        yield 'France' => [Area::FRANCE];
        yield 'Belgium' => [Area::BELGIUM];
    }

    #[Test]
    #[DataProvider('areaProvider')]
    public function toArrayUsesAreaValue(Area $area): void
    {
        $headers = $this->buildHeaders(area: $area);

        self::assertSame($area->value, $headers->toArray()[MessageHeaders::KEY_AREA]);
    }

    // -------------------------------------------------------------------------
    // Helpers
    // -------------------------------------------------------------------------

    private function buildHeaders(
        Area $area = Area::FRANCE,
        string $from = 'test-app',
        MessageType $messageType = MessageType::LOG,
        ?string $trackId = 'fixed-track-id',
        ?\DateTimeImmutable $dateTime = null,
        ?\DateTimeImmutable $dateTimeOriginal = null,
        ?string $fromOriginal = null,
        ?string $trackIdOriginal = null,
        string $version = MessageHeaders::DEFAULT_VERSION,
    ): MessageHeaders {
        return new MessageHeaders(
            area: $area,
            from: $from,
            messageType: $messageType,
            trackId: $trackId,
            dateTime: $dateTime,
            dateTimeOriginal: $dateTimeOriginal,
            fromOriginal: $fromOriginal,
            trackIdOriginal: $trackIdOriginal,
            version: $version,
        );
    }
}
